package migrate_test

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"log/slog"
	"time"

	"github.com/go-rio/migrate"
)

type role string

const (
	roleAdmin  role = "admin"
	roleMember role = "member"
)

// Applications register migrations from init functions in a migrations
// package imported for effect.
func init() {
	migrate.Add("20260708100000_create_users", func(s *migrate.Schema) {
		s.Create("users", func(t *migrate.Table) {
			t.ID()
			t.String("email").Unique()
			t.String("name", 100)
			t.Enum("role", roleAdmin, roleMember).Default(roleMember)
			t.Timestamps()
		})
	})

	migrate.Add("20260708110000_create_posts", func(s *migrate.Schema) {
		s.Create("posts", func(t *migrate.Table) {
			t.ID()
			t.ForeignID("user_id").Constrained().CascadeOnDelete()
			t.String("title")
			t.Text("body").Nullable()
			t.JSON("meta").Nullable()
			t.Index("user_id", "title")
		})
	})
}

// New wraps a caller-owned *sql.DB; the dialect must match the driver, and
// options tune locking, checksums, safety, and logging.
func ExampleNew() {
	db, err := sql.Open("pgx", "postgres://localhost/app") // driver of your choice
	if err != nil {
		log.Fatal(err)
	}
	defer func() { _ = db.Close() }()

	m, err := migrate.New(db, migrate.Postgres,
		migrate.WithLogger(slog.Default()),
		migrate.WithLockTimeout(2*time.Minute),
		migrate.WithStrictChecksum(),
		migrate.WithSafety(migrate.SafetyStrict),
	)
	if err != nil {
		log.Fatal(err)
	}

	statuses, err := m.Status(context.Background())
	if err != nil {
		log.Fatal(err)
	}
	for _, st := range statuses {
		fmt.Printf("%s applied=%t drifted=%t\n", st.Name, st.Applied, st.Drifted)
	}
}

// Up applies pending migrations as one batch, then changed repeatables; Plan
// previews the SQL and safety findings first.
func ExampleMigrator_Up() {
	db, err := sql.Open("pgx", "postgres://localhost/app")
	if err != nil {
		log.Fatal(err)
	}
	defer func() { _ = db.Close() }()

	m, err := migrate.New(db, migrate.Postgres)
	if err != nil {
		log.Fatal(err)
	}

	ctx := context.Background()
	plans, err := m.Plan(ctx)
	if err != nil {
		log.Fatal(err)
	}
	for _, p := range plans {
		fmt.Printf("-- %s: %d statements, %d warnings\n", p.Name, len(p.Statements), len(p.Warnings))
	}
	if err := m.Up(ctx); err != nil {
		log.Fatal(err)
	}
}

// Builders reverse themselves; raw SQL and Go functions discard information,
// so a migration using them declares its rollback with WithDown.
func ExampleAdd() {
	migrate.Add("20260709120000_backfill_names",
		func(s *migrate.Schema) {
			s.Table("users", func(t *migrate.Table) {
				t.String("display_name").Nullable()
			})
			s.Run(func(ctx context.Context, db migrate.DB) error {
				_, err := db.ExecContext(ctx, "UPDATE users SET display_name = name WHERE display_name IS NULL")
				return err
			})
		},
		migrate.WithDown(func(s *migrate.Schema) {
			s.Table("users", func(t *migrate.Table) {
				t.DropColumn("display_name")
			})
		}),
	)
}

// Collection.SQL renders migrations without a database.
func ExampleCollection_SQL() {
	c := migrate.NewCollection()
	c.Add("20260708100000_create_teams", func(s *migrate.Schema) {
		s.Create("teams", func(t *migrate.Table) {
			t.ID()
			t.String("name").Unique()
		})
	})

	plans, err := c.SQL(migrate.Postgres)
	if err != nil {
		log.Fatal(err)
	}
	for _, p := range plans {
		fmt.Printf("-- %s\n", p.Name)
		for _, stmt := range p.Statements {
			fmt.Printf("%s;\n", stmt)
		}
	}
	// Output:
	// -- 20260708100000_create_teams
	// CREATE TABLE "teams" (
	// 	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	// 	"name" VARCHAR(255) NOT NULL
	// );
	// CREATE UNIQUE INDEX "teams_name_unique" ON "teams" ("name");
}

// ClickHouse tables require an explicit storage engine.
func Example_clickHouse() {
	c := migrate.NewCollection()
	c.Add("20260809100000_create_events", func(s *migrate.Schema) {
		s.Create("events", func(t *migrate.Table) {
			t.UUID("id")
			t.String("tenant_id")
			t.TimestampTz("occurred_at")
			t.JSON("payload")
			t.ClickHouseEngine(
				"MergeTree() PARTITION BY toYYYYMM(occurred_at) " +
					"ORDER BY (tenant_id, occurred_at)",
			)
		})
	})

	db, err := sql.Open("clickhouse", "clickhouse://localhost:9000/default")
	if err != nil {
		log.Fatal(err)
	}
	defer func() { _ = db.Close() }()

	m, err := migrate.New(db, migrate.ClickHouse,
		migrate.WithCollection(c),
		migrate.WithoutLock(), // the deploy system must serialize this call
	)
	if err != nil {
		log.Fatal(err)
	}
	if err := m.Up(context.Background()); err != nil {
		log.Fatal(err)
	}
}
