package migrate

import (
	"strings"
	"testing"
)

func TestPartitionedParentCreate(t *testing.T) {
	parent := func(s *Schema) {
		s.Create("inventory_log", func(t *Table) {
			t.ID()
			t.TimestampTz("event_at")
			t.PartitionByRange("event_at")
		})
	}
	pg := compileSchema(t, Postgres, parent)
	if want := `) PARTITION BY RANGE ("event_at")`; !strings.Contains(pg[0], want) {
		t.Fatalf("postgres create = %s, want suffix %s", pg[0], want)
	}
	assertErrContains(t, compileErr(MySQL, parent), "PostgreSQL-only")
	assertErrContains(t, compileErr(SQLite, parent), "PostgreSQL-only")
}

func TestPartitionChildren(t *testing.T) {
	got := compileSchema(t, Postgres, func(s *Schema) {
		s.CreatePartition("log_202609", "inventory_log", ForValuesFromTo("2026-09-01", "2026-10-01"))
		s.CreatePartition("log_h0", "snapshot", ForValuesWith(8, 0))
		s.CreatePartition("log_us", "orders", ForValuesIn("US", "CA"))
		s.CreateDefaultPartition("log_default", "inventory_log")
		s.AttachPartition("inventory_log", "log_202610", ForValuesFromTo("2026-10-01", "2026-11-01"))
		s.DetachPartition("inventory_log", "log_202609")
	})
	assertSQL(t, got, []string{
		`CREATE TABLE "log_202609" PARTITION OF "inventory_log" FOR VALUES FROM ('2026-09-01') TO ('2026-10-01')`,
		`CREATE TABLE "log_h0" PARTITION OF "snapshot" FOR VALUES WITH (MODULUS 8, REMAINDER 0)`,
		`CREATE TABLE "log_us" PARTITION OF "orders" FOR VALUES IN ('US', 'CA')`,
		`CREATE TABLE "log_default" PARTITION OF "inventory_log" DEFAULT`,
		`ALTER TABLE "inventory_log" ATTACH PARTITION "log_202610" FOR VALUES FROM ('2026-10-01') TO ('2026-11-01')`,
		`ALTER TABLE "inventory_log" DETACH PARTITION "log_202609"`,
	})
}

func TestPartitionInverse(t *testing.T) {
	inv, err := (&createPartition{child: "c", parent: "p", bound: &PartitionBound{kind: "hash"}}).inverse()
	if err != nil {
		t.Fatal(err)
	}
	if d, ok := inv.(*dropTable); !ok || d.name != "c" {
		t.Fatalf("createPartition inverse = %#v", inv)
	}
	inv, err = (&attachPartition{parent: "p", child: "c"}).inverse()
	if err != nil {
		t.Fatal(err)
	}
	if d, ok := inv.(*detachPartition); !ok || d.child != "c" {
		t.Fatalf("attachPartition inverse = %#v", inv)
	}
	if _, err := (&detachPartition{parent: "p", child: "c"}).inverse(); err == nil {
		t.Fatal("detach must be irreversible")
	}
}

func TestPartitionValidation(t *testing.T) {
	err := compileErr(Postgres, func(s *Schema) {
		s.Table("t", func(t *Table) { t.PartitionByRange("x") })
	})
	assertErrContains(t, err, "Schema.Create")
	err = compileErr(Postgres, func(s *Schema) {
		s.Create("t", func(t *Table) {
			t.ID()
			t.PartitionByRange("a")
			t.PartitionByHash("b")
		})
	})
	assertErrContains(t, err, "two partitioning methods")
	err = compileErr(Postgres, func(s *Schema) {
		s.CreatePartition("c", "p", PartitionBound{})
	})
	assertErrContains(t, err, "needs a bound")
	assertErrContains(t, compileErr(MySQL, func(s *Schema) {
		s.CreatePartition("c", "p", ForValuesWith(4, 1))
	}), "PostgreSQL-only")
}

// A table-level Primary may include the identity column — partitioned
// parents need the composite form; SQLite's rowid alias cannot.
func TestCompositePrimaryWithIdentity(t *testing.T) {
	def := func(s *Schema) {
		s.Create("pt", func(t *Table) {
			t.BigInteger("id").AutoIncrement()
			t.TimestampTz("at")
			t.Primary("id", "at")
		})
	}
	pg := compileSchema(t, Postgres, def)
	if want := `"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL`; !strings.Contains(pg[0], want) {
		t.Fatalf("identity must render without an inline PK:\n%s", pg[0])
	}
	if want := `PRIMARY KEY ("id", "at")`; !strings.Contains(pg[0], want) {
		t.Fatalf("composite PK lost:\n%s", pg[0])
	}
	my := compileSchema(t, MySQL, def)
	if want := "PRIMARY KEY (`id`, `at`)"; !strings.Contains(my[0], want) {
		t.Fatalf("mysql composite PK lost:\n%s", my[0])
	}
	assertErrContains(t, compileErr(SQLite, def), "sole primary key")

	// Without the explicit composite, the guard still fires.
	err := compileErr(Postgres, func(s *Schema) {
		s.Create("pt", func(t *Table) {
			t.ID()
			t.TimestampTz("at")
			t.Primary("at")
		})
	})
	assertErrContains(t, err, "combines an auto-incrementing")
}
