package migrate

import (
	"context"
	"strings"
	"testing"
)

func TestColumnKindMapping(t *testing.T) {
	declare := func(s *Schema) {
		s.Create("kitchen", func(t *Table) {
			t.ID("pk")
			t.String("str")
			t.Char("chr", 2)
			t.Text("txt")
			t.TinyInteger("tiny")
			t.SmallInteger("small")
			t.Integer("num")
			t.BigInteger("big")
			t.Boolean("flag")
			t.Decimal("dec", 8, 3)
			t.Float("f32")
			t.Double("f64")
			t.Date("d")
			t.Time("tm")
			t.DateTime("dtm")
			t.Timestamp("ts")
			t.TimestampTz("tstz")
			t.JSON("doc")
			t.UUID("uid")
			t.Binary("bin")
			t.Enum("mood", "up", "down")
			t.Column("raw", "MACADDR")
			t.SoftDeletes()
		})
	}
	want := map[string]struct{ pg, my, lite string }{
		`"pk"`:         {"BIGINT GENERATED BY DEFAULT AS IDENTITY", "BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT"},
		`"str"`:        {"VARCHAR(255)", "VARCHAR(255)", "VARCHAR(255)"},
		`"chr"`:        {"CHAR(2)", "CHAR(2)", "CHAR(2)"},
		`"txt"`:        {"TEXT", "LONGTEXT", "TEXT"},
		`"tiny"`:       {"SMALLINT", "TINYINT", "INTEGER"},
		`"small"`:      {"SMALLINT", "SMALLINT", "INTEGER"},
		`"num"`:        {"INTEGER", "INT", "INTEGER"},
		`"big"`:        {"BIGINT", "BIGINT", "INTEGER"},
		`"flag"`:       {"BOOLEAN", "TINYINT(1)", "BOOLEAN"},
		`"dec"`:        {"NUMERIC(8, 3)", "DECIMAL(8, 3)", "NUMERIC(8, 3)"},
		`"f32"`:        {"REAL", "FLOAT", "REAL"},
		`"f64"`:        {"DOUBLE PRECISION", "DOUBLE", "REAL"},
		`"d"`:          {"DATE", "DATE", "DATE"},
		`"tm"`:         {"TIME", "TIME", "TIME"},
		`"dtm"`:        {"TIMESTAMP", "DATETIME(6)", "DATETIME"},
		`"ts"`:         {"TIMESTAMP", "DATETIME(6)", "DATETIME"},
		`"tstz"`:       {"TIMESTAMPTZ", "DATETIME(6)", "DATETIME"},
		`"doc"`:        {"JSONB", "JSON", "TEXT"},
		`"uid"`:        {"UUID", "CHAR(36)", "CHAR(36)"},
		`"bin"`:        {"BYTEA", "LONGBLOB", "BLOB"},
		`"mood"`:       {"VARCHAR(255)", "ENUM('up', 'down')", "TEXT"},
		`"raw"`:        {"MACADDR", "MACADDR", "MACADDR"},
		`"deleted_at"`: {"TIMESTAMPTZ", "DATETIME(6)", "DATETIME"},
	}

	pg := compileSchema(t, Postgres, declare)[0]
	my := compileSchema(t, MySQL, declare)[0]
	lite := compileSchema(t, SQLite, declare)[0]
	for col, w := range want {
		myCol := strings.ReplaceAll(col, `"`, "`")
		if !strings.Contains(pg, col+" "+w.pg) {
			t.Errorf("postgres: want %s %s\nin: %s", col, w.pg, pg)
		}
		if !strings.Contains(my, myCol+" "+w.my) {
			t.Errorf("mysql: want %s %s\nin: %s", myCol, w.my, my)
		}
		if !strings.Contains(lite, col+" "+w.lite) {
			t.Errorf("sqlite: want %s %s\nin: %s", col, w.lite, lite)
		}
	}
}

func TestModifierChains(t *testing.T) {
	got := compileSchema(t, MySQL, func(s *Schema) {
		s.Create("orders", func(t *Table) {
			t.Integer("code").Unsigned().Primary()
			t.Unique("code", "region").Name("orders_code_region_key")
			t.Foreign("region").References("regions", "code").
				Name("orders_region_fk").
				RestrictOnDelete().
				CascadeOnUpdate()
			t.Integer("region")
		})
		s.Table("orders", func(t *Table) {
			t.String("note").Nullable().First()
		})
	})
	create := got[0]
	for _, frag := range []string{
		"`code` INT UNSIGNED NOT NULL",
		"PRIMARY KEY (`code`)",
		"CONSTRAINT `orders_region_fk` FOREIGN KEY (`region`) REFERENCES `regions` (`code`) ON DELETE RESTRICT ON UPDATE CASCADE",
	} {
		if !strings.Contains(create, frag) {
			t.Errorf("create should contain %q, got:\n%s", frag, create)
		}
	}
	if got[1] != "CREATE UNIQUE INDEX `orders_code_region_key` ON `orders` (`code`, `region`)" {
		t.Errorf("named unique index, got: %s", got[1])
	}
	if got[2] != "ALTER TABLE `orders` ADD COLUMN `note` VARCHAR(255) FIRST" {
		t.Errorf("first placement, got: %s", got[2])
	}
}

func TestForeignKeyActionVariants(t *testing.T) {
	got := compileSchema(t, Postgres, func(s *Schema) {
		s.Create("t", func(t *Table) {
			t.ForeignID("a_id").References("parents").NullOnDelete()
			t.ForeignID("b_id").Constrained("parents").RestrictOnDelete()
			t.Foreign("c_id").References("parents").NoActionOnDelete().RestrictOnUpdate()
			t.Foreign("d_id").References("parents").NullOnUpdate()
			t.BigInteger("c_id")
			t.BigInteger("d_id")
		})
	})
	create := got[0]
	for _, frag := range []string{
		`FOREIGN KEY ("a_id") REFERENCES "parents" ("id") ON DELETE SET NULL`,
		`FOREIGN KEY ("b_id") REFERENCES "parents" ("id") ON DELETE RESTRICT`,
		`FOREIGN KEY ("c_id") REFERENCES "parents" ("id") ON DELETE NO ACTION ON UPDATE RESTRICT`,
		`FOREIGN KEY ("d_id") REFERENCES "parents" ("id") ON UPDATE SET NULL`,
	} {
		if !strings.Contains(create, frag) {
			t.Errorf("missing %q in:\n%s", frag, create)
		}
	}
}

func TestForeignColumnChainsThroughColumnModifiers(t *testing.T) {
	got := compileSchema(t, Postgres, func(s *Schema) {
		s.Create("posts", func(t *Table) {
			t.ForeignID("author_id").Constrained("users").NullOnDelete().Nullable().Index()
			t.ForeignID("editor_id").Constrained("users").Unique()
		})
	})
	create := got[0]
	if !strings.Contains(create, `"author_id" BIGINT`) || strings.Contains(create, `"author_id" BIGINT NOT NULL`) {
		t.Errorf("author_id should be nullable, got:\n%s", create)
	}
	assertSQL(t, got[1:], []string{
		`CREATE INDEX "posts_author_id_index" ON "posts" ("author_id")`,
		`CREATE UNIQUE INDEX "posts_editor_id_unique" ON "posts" ("editor_id")`,
	})
}

func TestPackageLevelAddUsesDefaultCollection(t *testing.T) {
	name := "zz_test_pkg_add_" + t.Name()
	Add(name, func(s *Schema) {
		s.Create("pkg_add_probe", func(t *Table) { t.ID() })
	})
	f := newFakeDB()
	db := f.open()
	t.Cleanup(func() { _ = db.Close() })
	m, err := New(db, SQLite)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	if err := m.Up(context.Background()); err != nil {
		t.Fatalf("Up: %v", err)
	}
	if len(f.loggedContaining("pkg_add_probe")) == 0 {
		t.Error("the default collection migration should have run")
	}
}

func TestGeneratedColumns(t *testing.T) {
	declare := func(s *Schema) {
		s.Create("people", func(t *Table) {
			t.ID()
			t.String("first")
			t.String("last")
			t.String("full").StoredAs("first || ' ' || last")
			t.JSON("meta").Nullable()
			t.String("kind", 32).VirtualAs("json_extract(meta, '$.kind')").Nullable()
		})
	}
	pg := compileSchema(t, Postgres, declare)[0]
	for _, frag := range []string{
		`"full" VARCHAR(255) GENERATED ALWAYS AS (first || ' ' || last) STORED NOT NULL`,
		`"kind" VARCHAR(32) GENERATED ALWAYS AS (json_extract(meta, '$.kind')) VIRTUAL`,
	} {
		if !strings.Contains(pg, frag) {
			t.Errorf("postgres missing %q in:\n%s", frag, pg)
		}
	}
	my := compileSchema(t, MySQL, declare)[0]
	if !strings.Contains(my, "`full` VARCHAR(255) GENERATED ALWAYS AS (first || ' ' || last) STORED NOT NULL") {
		t.Errorf("mysql stored generated column, got:\n%s", my)
	}
	lite := compileSchema(t, SQLite, declare)[0]
	if !strings.Contains(lite, `"full" VARCHAR(255) NOT NULL GENERATED ALWAYS AS (first || ' ' || last) STORED`) {
		t.Errorf("sqlite stored generated column, got:\n%s", lite)
	}
}

func TestGeneratedColumnValidation(t *testing.T) {
	cases := map[string]func(*Table){
		"with default":        func(t *Table) { t.String("x").StoredAs("a").Default("y") },
		"with use current":    func(t *Table) { t.Timestamp("x").StoredAs("a").UseCurrent() },
		"with auto increment": func(t *Table) { t.Integer("x").AutoIncrement().StoredAs("a") },
	}
	for name, decl := range cases {
		t.Run(name, func(t *testing.T) {
			m := migrationOf(t, func(s *Schema) { s.Create("t", func(tb *Table) { decl(tb) }) })
			if _, err := m.upOps(); err == nil {
				t.Fatal("expected a declaration error")
			}
		})
	}
}

func TestCollation(t *testing.T) {
	declare := func(name string) func(*Schema) {
		return func(s *Schema) {
			s.Create("users", func(t *Table) {
				t.ID()
				t.String("email").Collation(name).Unique()
			})
		}
	}
	if got := compileSchema(t, Postgres, declare("C"))[0]; !strings.Contains(got, `"email" VARCHAR(255) COLLATE "C" NOT NULL`) {
		t.Fatalf("postgres: %s", got)
	}
	if got := compileSchema(t, MySQL, declare("utf8mb4_bin"))[0]; !strings.Contains(got, "`email` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL") {
		t.Fatalf("mysql: %s", got)
	}
	if got := compileSchema(t, SQLite, declare("NOCASE"))[0]; !strings.Contains(got, `"email" VARCHAR(255) COLLATE NOCASE NOT NULL`) {
		t.Fatalf("sqlite: %s", got)
	}
	clickhouse := func(s *Schema) {
		s.Create("users", func(t *Table) {
			t.String("email").Collation("en")
			t.ClickHouseEngine("MergeTree() ORDER BY tuple()")
		})
	}
	assertErrContains(t, compileErr(ClickHouse, clickhouse), "collation")

	change := func(name string) func(*Schema) {
		return func(s *Schema) {
			s.Table("users", func(t *Table) { t.String("email").Collation(name).Change() })
		}
	}
	if got := compileSchema(t, Postgres, change("C"))[0]; got != `ALTER TABLE "users" ALTER COLUMN "email" TYPE VARCHAR(255) COLLATE "C"` {
		t.Fatalf("postgres change: %s", got)
	}
	assertSQL(t, compileSchema(t, MySQL, change("utf8mb4_bin")), []string{
		"ALTER TABLE `users` MODIFY COLUMN `email` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL",
	})
}
